config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'sessions#login'
  resources :quests do
    member do
      get :expected
      get :complete
      get :results
    end
    resources :tasks do
      post 'attempt', on: :member
    end
  end

  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy'
end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
  RESULT_TYPES = %w(success fail)
  belongs_to :task
  belongs_to :team

  validates_inclusion_of :result, in: RESULT_TYPES
  validates_presence_of :code, if: Proc.new{task.code_task?}

  before_validation :get_result

  scope :success, -> {where result: 'success'}

  def success?
    result == 'success'
  end

  private

    def get_result
      p task.success_code.to_s.downcase
      p code.to_s.downcase
      self.result = task.success_code.to_s.downcase == code.to_s.downcase ? 'success' : 'fail'
    end
end

app/models/quest.rb
class Quest < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  has_many :teams, dependent: :destroy

  validates_presence_of :start_at, :end_at, :name

  scope :published, -> {where published: true}
  scope :available_for_results, -> {where "end_at < ?", Time.now-1.hour}

  def in_progress?
    Time.now > start_at && end_at > Time.now
  end

  def count_tasks
    tasks.published.count
  end

  def results_available?
    Time.now > end_at
  end

  def finished_teams
    teams.admitted.joins(:attempts).where(attempts: {result: 'success', task_id: tasks.published.last}).order('attempts.created_at')
  end

  def place_for_team(team)
    finished_teams.index(team)+1
  end
end

app/models/settings.rb
class Settings < RailsSettings::CachedSettings
end

app/models/task.rb
class Task < ActiveRecord::Base
  ANSWERS_TYPES = %w(code photo)
  belongs_to :quest
  has_many :attempts

  validates_presence_of :name, :answer_type
  validates_presence_of :success_code, if: Proc.new{code_task?}
  validates_inclusion_of :answer_type, in: ANSWERS_TYPES

  scope :published, -> {where published: true}

  def code_task?
    answer_type == 'code'
  end

  def completed_by?(team)
    Attempt.where(result: 'success', task: self, team: team).first.present?
  end

  def number_in_quest_list
    quest.tasks.published.index(self)+1
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :quest
  has_many :attempts

  validates_presence_of :name, :access_code

  scope :admitted, -> {where is_admitted: true}

  def current_task
    quest.tasks.published.each do |t|
      return t unless t.completed_by? self
    end
  end


  def current_progress
    (attempts.success.count/quest.count_tasks.to_f*100).to_i
  end

  def complete_quest?
    current_progress == 100
  end

  def time_of_compete
    attempts.success.last.created_at
  end

  def transit_time
    (time_of_compete - quest.start_at).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :associate_with_team
  before_action :check_team

  private

    def associate_with_team
      @team ||= Team.admitted.find_by access_code: session[:access_code]
    end

    def check_team
      unless params[:controller].match(/^rails_admin/)
        redirect_to root_path unless @team.present?
      end
    end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :set_quest
  before_action :check_expected_time, only: :expected
  before_action :check_team, except: :results
  before_action :check_time_for_result_displaying, only: :results

  def show
    redirect_to quest_task_path(@quest, @team.current_task)
  end

  def results
    @finished_teams = @quest.finished_teams
  end

  private

    def set_quest
      @quest = Quest.published.find params[:id]
    end

    def check_expected_time
      redirect_to quest_task_path(@quest, @team.current_task) if @quest.in_progress?
    end

    def check_time_for_result_displaying
      unless @quest.results_available?
        flash[:error] = t 'results.access_denied'
        redirect_to root_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :check_team, except: [:create, :login]

  def create
    if params[:login].present?
      @team = Team.admitted.find_by access_code: params[:login][:code]
      
      if @team.present?
        session[:access_code] = @team.access_code
      end
    end
    redirect_to root_path
  end

  def destroy
    session.delete(:access_code)
    redirect_to root_path
  end

  def login
    redirect_to quest_path(@team.quest) if @team.present?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task
  before_action :check_start_time
  before_action :check_progress, only: :show
  before_action :check_completing_task, only: :show

  def attempt
    if params[:attempt].present?
      if @task.code_task?
        @attempt = Attempt.create(task: @task, team: @team, code: params[:attempt][:code])
        if @attempt.success?
          flash[:notice] = t('code.success')
        else
          flash[:error] = t('code.incorrect')
        end
        redirect_to quest_task_path(@task.quest, @team.current_task)
      end
    end
  end

  private

    def set_task
      @task = Task.published.find params[:id]
    end

    def check_start_time
      return if @task.quest.in_progress?
      redirect_to expected_quest_path if Time.now < @task.quest.start_at
    end

    def check_progress
      redirect_to complete_quest_path(@task.quest) if @team.complete_quest?
    end

    def check_completing_task
      redirect_to quest_task_path(@team.quest, @team.current_task) if @task.completed_by? @team
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="ru"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : Settings.main_title
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    #jumbo.jumbotron.text-center
      .container#main-container
        = link_to root_path do
            = image_tag 'logo.png', size: '152x42'
        - if @team.present?
          .row
            p.pull-right
              = @team.name
              |&nbsp;
              = link_to 'Выход', login_path, method: :delete
        hr
        = bootstrap_flash
        = yield
        hr
        .col-md-12.text-center
          .well style="background-color: #6EE3E7; color: #fff; font-size: 19px;"
            = link_to 'http://d4mk0.me', target: '_blank', style: 'color: #fff; text-decoration: underline' do
              |Разработал Дамир Коньков
              br
              |Developed by Damir Konkov
              br
              |d4mk0.me
    = render 'shared/yandex_metrika'

app/views/login/login.html.slim
h1 = t('login.title')
= form_for :login do |f|
  .form-group
    = f.text_field :code, placeholder: t('login.input_placeholder'), class: 'form-control'
  .form-group= f.submit t('login.button_title'), class: 'btn btn-danger'

app/views/quests/complete.html.slim
.progress.progress-striped.active
  .progress-bar.progress-bar-success style=("width: 100%;") 
h1 Игра окончена!
div
  | Поздравляем!
div
  | Спасибо за участие!
div
  | Результаты будут доступны через некоторое время
  |&nbsp;
  = link_to 'по ссылке', results_quest_path(@quest)
div
  b Расскажите о нас свом друзьями и закомым. поделитесь ссылкой. http://экодозор.рф

app/views/quests/expected.html.slim
h1
  |Квест начнется в  
  = @quest.start_at.strftime("%H:%M %d.%m.%Y")
.well
  h2
    string = @quest.name
  p = @quest.description

app/views/quests/results.html.slim
h1 Результаты игры
table.table.table-hover#results_table
  thead
    tr
      th Место
      th Команда
      th Время окончания
      th Общее время прохождения
  tbody
    - @finished_teams.each do |t|
      tr
        td = @quest.place_for_team t
        td = t.name
        td = t.time_of_compete.strftime("%H:%M:%S %d.%m.%Y")
        td = t.transit_time

app/views/shared/_yandex_metrika.html.slim
- if Rails.env.production?
  /! Yandex.Metrika counter
  javascript:
    (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
        try {
          w.yaCounter26685678 = new Ya.Metrika({id:26685678,
            webvisor:true,
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true,
            trackHash:true});
        } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
  noscript
    div
      img alt="" src="//mc.yandex.ru/watch/26685678" style=("position:absolute; left:-9999px;") /
  /! /Yandex.Metrika counter

app/views/tasks/show.html.slim
.progress.progress-striped.active
  .progress-bar style=("width: #{@team.current_progress}%;") 
h1
  |Задание 
  = "##{@task.number_in_quest_list}"
.well
  h2
    string = @task.name
  p = @task.description
= form_for :attempt, url: attempt_quest_task_path(@task.quest, @task), html: { class: 'form-horizontal', role: :form, miltipart: true } do |f|
  - if @task.code_task?
    .form-group
      = f.text_field :code, class: 'form-control', placeholder: "Введите найденный код"
  - else
    .form-group
      label Загрузите фото
      = f.file_field :photo, class: 'form-control'
  button.btn.btn-danger type="submit" 
      | Click!